---
--- Generated by Luanalysis
--- Created by 20247.
--- DateTime: 2023/3/21 13:11
---
-- 优惠券id
local voucherId = ARGV[1]
-- 用户id
local userId = ARGV[2]
-- 订单id
local orderId = ARGV[3]

-- 库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 订单key
local orderKey = 'seckill:order:' .. voucherId

-- 业务
if(tonumber(redis.call('get',stockKey)) <= 0)then
    -- 库存不足，返回1
    return 1
end
if(redis.call('sismember',orderKey,userId) == 1)then
    -- 重复下单，返回2
    return 2
end
-- 扣减库存
redis.call('incrby',stockKey,-1)
-- 添加订单
redis.call('sadd',orderKey,userId)
-- 发送消息到消息队列
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
-- 操作成功，返回0
return 0